### ISSUE TITLE
PropTypes not set correctly

### ISSUE THREAD

**Issue by vikkio88** [kusti8/proton-native#109]
Hi guys,
you did set proptypes on components as follows `ComponentName.PropTypes` but that is not the correct syntax, as it should be lower camel case `ComponentName.PropTypes`, so passing the wrong `propTypes` is not throwing any warning for me, nor is auto-completing on my IDE

**Comment by mischnic** [comment]
proton-native checks them (not React):

https://github.com/kusti8/proton-native/blob/d37dae1299527cfc51905b8eccdc1d398ebe413f/src/components/DesktopComponent.js#L54-L59

And it does work:

```jsx
<TextInput stretchy="false" />
```

->

```
Warning: Failed prop type: Invalid prop `stretchy` of type `string` supplied to `Entry`, expected `boolean`.
```

@kusti8 is there a specific reason you did it this way ?

**Comment by vikkio88** [comment]
it would be nice to make adopt the same standard as react, dont you think? 
https://reactjs.org/docs/typechecking-with-proptypes.html

**Comment by kusti8** [comment]
It's because when `createElement` makes a class, the React system does not know about it so it doesn't check props. React only checks props on React components, which the base components are not. I'll change the name to be more in line with React standards, but if you remove the checkProp line, then it doesn't work.
