### ISSUE TITLE
Please clarify in README or docs which Windows version is supported

### ISSUE THREAD

**Issue by fabriziomoscon** [kusti8/proton-native#153]
We had a deployment issue because Electron seems not to be working on Windows Server 2000.
I was wondering what are the OS requirements for `proton-native`

**Comment by parro-it** [comment]
Electron is not required in production, only for development.
Anyway, being proton-native based on `libui-node`, I think you'll have problem getting it to work on Windows 2000, since it support only Vista or newer:

https://github.com/parro-it/libui-node#supported-platforms

It can work... I don't know, I'm just never try it...

**Comment by fabriziomoscon** [comment]
thanks
