### ISSUE TITLE
Is there a way to display video in Proton native app?

### ISSUE THREAD

**Issue by bhaskardabhi-oviyum** [kusti8/proton-native#219]
Hi,

I want to build an app which displays video feeds. Is there a way in proton to display video in app? Like `<Video>` element or something?.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.

**Comment by roman01la** [comment]
@kusti8 Hey. I'd like to dig in and try to implement video playback, I'd appreciate any initial input

**Comment by kusti8** [comment]
With Qt there is a guide here: https://doc.qt.io/qt-5/videooverview.html#playing-video-in-c You would use the QVideoWidget instead of the other widget. You can just copy one of the other classes, and then that class would contain QMediaPlayer and the QVideoWidget (and you would set the media just by calling set media: `player->setMedia(QUrl::fromLocalFile("/Users/me/Music/coolsong.mp3"));`) Also please make a new issue to track this.

**Comment by roman01la** [comment]
@kusti8 Alright, sounds good. Thanks!
