### ISSUE TITLE
Project similar to proton-native

### ISSUE THREAD

**Issue by parro-it** [kusti8/proton-native#22]
Are you aware of [react-libui](https://github.com/parro-it/react-libui)?
Even if it is now under my account, it is entirely the work of @paulbgd.

I think to make you aware of that, even if it's probably not production-ready, it could be worth to give it a look...

**Comment by kusti8** [comment]
Yeah I came across it just as I was finishing this project. I thought I would release this anyway, and work hard on the documentation so that it would be usable. I also tried to abstract some things from libui into props and try and make it closer to React.  This isn't production ready either, because of libui.

I appreciate your work on libui-node and if @PaulBGD, wants to, I would welcome his help.

**Comment by parro-it** [comment]
> I thought I would release this anyway, and work hard on the documentation so that it would be usable.

A good choice and you did a great job so far!

> I appreciate your work on libui-node and if @PaulBGD, wants to, I would welcome his help.

Thank you a lot! I didn't ask him, but I guess he already noticed your project...

**Comment by PaulBGD** [comment]
Thanks for the shout-out @parro-it, but react-libui was made for an older version of react and has a lot of duplicate code. This project looks better constructed than anything I made. Best of luck!
