### ISSUE TITLE
proton-packager

### ISSUE THREAD

**Issue by mischnic** [kusti8/proton-native#43]
I have built a cli tool to package proton apps (currently only macOS bundles are supported).
Maybe there is someone who knows how the linux (or windows) packaging should work and would like to contribute (platform-independent parts can be reused).

https://github.com/mischnic/proton-packager

This could be added the Mac section of the "Packaging" docs.

#39 @GordyGordy This will create a proper .app bundle.

---

The main thing on macOS, that is keeping bundles from being indistinguishable from native apps, is #13.

**Comment by kusti8** [comment]
I've been experimenting with nexe and pkg and I've got them working. I would prefer creating a single binary this way, rather than creating a .app with what you've done. I would love the keep the cli tool, but replace the packaging with nexe. I just need to finish up testing and then I'll make a write-up

**Comment by kusti8** [comment]
Ok, so `pkg` works. I'm going to add this to `create-proton-app`. One problem which you can still solve is the fact that nbind.node and the libui library still have to be present outside the executable.

**Comment by mischnic** [comment]
Pkg and nexe both create a single binary file regardless of the platform (please correct me if I'm wrong). Double-clicking such a file on macOS would first open a Terminal and the app itself would start. It's also not possible to give an icon to a single binary file which is then also visible in the Dock.

My solution:
![example_proton](https://user-images.githubusercontent.com/4586894/36946712-6b2b4b3a-1fc1-11e8-9bcb-bd2aea963733.png)

How it would look like on mac without an .app bundle:
![bildschirmfoto 2018-03-04 um 15 38 23](https://user-images.githubusercontent.com/4586894/36946761-29ca2a84-1fc2-11e8-9f33-a7f3692d0484.png)

**Comment by kusti8** [comment]
Ok. I'm still going to create a single binary using `pkg` and then you can create an .app from that.

**Comment by albe-rosado** [comment]
I see, this week me too will be working on packaging issues with nexe/pkg. I like what @mischnic has done, but something more cross-platform would be ideal. Although we could detect the user's platform an expose the right script for them in the package.json file: ie. 
In Mac:
``` js
{
  "name": "my-proton-app",
  "scripts": {
    "package": "proton-packager mac MyApp -f"
  },
  ...
}
```
And in Linux/Windows:
``` js
{
  "name": "my-proton-app",
  "scripts": {
    "package": "nexe --build"//or just `node build.js` and add nexe as dev dep.
  },
  ...
}
```
Other thing, @kusti8 having library files next to the binary file is not ideal but isn't too bad either, we can design a installer kind of thing that will expose a shortcut to the user and copy our files to other folder, in Linux, something like having an `my-app.desktop` file will get the user the app in their launcher in debian based distros (at least), and in Windows, I guess doing just a shortcut and sending our files to `C:\\program\ files\`. What do you think?

**Comment by mischnic** [comment]
I want thinking of integrating nexe/pkg into proton-packager, so the user could just pass `win` instead of `mac`.

**Comment by albe-rosado** [comment]
@mischnic yeah, that would be ideal.

**Comment by kusti8** [comment]
Yeah that sounds like a good idea. Libui-node may go statically linked
which would make it easier to package.

**Comment by albe-rosado** [comment]
I have been working in issuing appImages files for Linux, so with @mischnic piece and mine(in progress ), we will only need something similar for windows?

**Comment by albe-rosado** [comment]
Added the appImage packaging for Linux @kusti8 , @mischnic . Take a look at the gitter.

**Comment by develar** [comment]
I suggest you to join forces. I can add proton support to electron-builder. Despite the name, electron can be easily decoupled (actually, modules is already decoupled and some part of code even available as a separate internal tool app-builder https://github.com/develar/app-builder).

So, you can just implement specific for proton pars, and you get generic features that electron-builder provides:
* publishing
* a lot of targets (including cross-platform and bundled tools for any OS without manual installation by user)
* proven and tested implementation, since electron-builder is a well established and popular tool (e.g. Snapcraft team and AppImage team helps us directly).

**Comment by albe-rosado** [comment]
I think that would be a good idea, ideally, and this is what I'm working to achieve on `create-proton-app`(always open to feedback) is raw performance, as little dependencies as possible, and usability. That is why I have chosen to write bash scripts for appImages and MacOS app bundles. I don't know what you mean for "proton pars" @develar , at the end it depends on @kusti8  decision, if this is what we decide I will be happy to include that logic. In the other hand, the library you reference is written in Go if any bug is reported we would be relying on the maintainers of that library to get it fixed, It will affect the stability of this as well. I will be trying it out to see how it goes. I'm happy to see we may finally have a "one size fits all" kind of thing.

**Comment by mischnic** [comment]
The problem I see with create-proton-app is that distributing new script versions is quite hard because it is installed globally (create-react-app had this as well). Also, putting the script into the created project means that the user has to update it himself. This is why separate packagers are better suited (and they can be used in projects created without create-...-app).

> That is why I have chosen to write bash scripts for appImages

What if you wanted to package for linux on windows (after we got precompiled binaries for libui-node)? This is the reason why most scripts in the npm ecosystem are node scripts themselves.

> In the other hand, the library you reference is written in Go if any bug is reported we would be relying on the maintainers of that library to get it fixed, It will affect the stability of this as well

So what is better, creating an untested script from scratch or using an already tested tool?

**Comment by develar** [comment]
> write bash scripts for appImages and MacOS app bundles

electron-builder is able to produce AppImage on macOS/Linux and no need to install AppImage tools manually. The same for snap. And for other targets. "usability"

> what you mean for "proton pars"

1. Packaging. Transform user project into packable format, suitable for distributable formats (dmg, appimage, snap and so on)
2. Apply user project metadata (e.g. modify icon and file properties (windows executable))
3. Sign binaries
4. Package into distributable format.
5. Sign artifacts (required for for NSIS and DMG).
6. Publish binaries.

Here framework specific only first step (yes, because of performance, other steps can be also depends, for example, electron-builder tries to do all using in-memory and avoid file copying). "proton pars" means "how to transform user project into packable format" (step 1).

> the library you reference

Because of usability, NodeJS cannot be used for all raw and native things. Native node module it is hell (must be no native modules to ensure that users will not suffer). JS implementation of some things in most cases leads to bloated package ("as little dependencies as possible"). So, image tasks (electron-builder is able to produce icns or ico from one png file), downloading (multi-part downloader cannot b effectively implemented using NodeJS) and other low-level tasks implemented in Golang.

> we would be relying on the maintainers of that library to get it fixed

Golang is much more better suitable language for build tools. But in any case right now electron-builder implemented in TS. Golang used only for low-level tasks.

**Comment by albe-rosado** [comment]
mmm, I see, totally forgot the case when someone on windows wants to produce other platform binaries, LOL. I like Golang, and I like `app-builder`. @mischnic  right now you can use `create-proton-app` with `npx` so no need to install stuff globally. but I see your point on using shell scripts and you are right. I'm thinking on wrapping `app-builder ` with a node script and make it super generic, so anyone could package their binary to their favorite format from their home platform. That's definetely awesome. @develar

**Comment by develar** [comment]
Ok. If no one has some objections, I will incorporate https://github.com/mischnic/proton-packager into a new module proton-builder, that will use electron-builder-lib under the hood and will decouple electron related code.

For example, issues like https://github.com/mischnic/proton-packager/issues/3 will be in the past, since electron-builder is able correctly copy only production deps (including support for Yarn/Lerna workspaces).

**Comment by albe-rosado** [comment]
Awesome!!! :+1:  I just add that to the scripts and we will be done with packaging.

**Comment by mischnic** [comment]
👍

**Comment by kusti8** [comment]
Sounds good.

**Comment by develar** [comment]
I have done first part (download node and prepare app template, code is taken from https://github.com/mischnic/proton-packager/blob/master/src/mac.js) of required changes to electron-builder to support proton (btw, electron-builder also supports muon, so, electron was already a little bit decoupled).

* node downloading and extracting using Go, so, no dependency on decompress, no new nodejs dependencies. Change compared to `proton-packager` — to reduce download time, `tar.xz` is used instead of `tar.gz`.
* generated Info.plist now contains correct version.

electron-builder is not yet able to build Proton, I will continue (https://github.com/develar/electron-builder/commit/f20d7cc1254b9ee5c6a78321a94dec82b8d1dbc7#diff-d0d77e592f1e2eac7e50d28153a8d0c0). Next part — copying project files.

**Comment by mischnic** [comment]
@develar Two important things that (I think) are different to electron (just as a reminder):
- the `build` folder in `node_modules/libui-node` has to be deleted, because it is ~80mb big and not needed anymore. The file `node_modules/libui-node/nbind.node` has to stay (that was my problem in https://github.com/mischnic/proton-packager/issues/3).
- the source files need to be transpiled with babel, because we are using JSX.

**Comment by develar** [comment]
@mischnic Thanks. Also, as far I see, `libui-node/docs`, `libui-node/src` should be also ignored.

**Comment by mischnic** [comment]
Technically yes, but in total that's at most only 500kb.

**Comment by develar** [comment]
> the source files need to be transpiled with babel

It is a little bit strange for me, since it should be handled somehow outside of builder tool to be fully controlled by user... but I totally agree that this functionality should be fully integrated since most users will use runtime compilation during development.  

For example, electron-webpack is not supported by electron-builder, instead, electron-webpack provides special `files` configuration (https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/electron-builder.yml). Yes — another advantage of using electron-builder to package Proton is that you will get all functionality that was implemented and requested for Electron apps for last 3 years :) https://www.electron.build/configuration/contents 

So, it will be easy for user to package whatever complex project structure. But by default solution like electron-compile support (build on the fly without intermediate files) and how it is currently implemented in the proton-packager.

BTW — for Windows it is not good to have a lot of small files. Solution or https://github.com/pmq20/node-packer (on a first glance, development env will be very complex to setup), or WebPack bundle (easy solution, but requires changes to the app and can lead to runtime errors due to difference to development version). In any case for now I want to support Linux/macOS at first.

**Comment by mischnic** [comment]
Yes, a bundler would work as well, might even be faster running the app then.

I don't fully understand how electron-webpack and electron-bundler work together, but we can use that if they do.

**Comment by develar** [comment]
electron-builder supports packaging of Proton apps for macOS (will be released in 2 days, once polished and manually checked). All functionality of electron-builder is available, except file associations (easy to do) and auto-update.

Next, I will add support for Linux (easy) and Windows (easy, but not production ready because windows IO is poor, something like pkg should be used (https://github.com/zeit/pkg/issues/369)).

Do you have official icon for Proton? As a default if no user? I see that there is a logo, but need something suitable as a app icon (maybe just without words "proton native").

**Comment by mischnic** [comment]
👍 

Maybe something like this? (modified from https://github.com/kusti8/proton-native/blob/master/docs/images/icon_black.svg)

![logo](https://user-images.githubusercontent.com/4586894/37679646-d015eb50-2c81-11e8-86f8-afc0cf483545.png)


@kusti8 ?

**Comment by albe-rosado** [comment]
@develar  there will be some sort of docs for the new adaptation of electron-builder for proton, so i can reflect the changes in the cli app?

**Comment by develar** [comment]
Upcoming electron-builder 21.7.0 supports packaging for macOS and Linux. 

* executable name changed from hardcoded `main` to proper (e.g. for example app it is `notepad`)
* for Linux all functionality is supported, including auto-update (but only on low-level, client electron-updater is not yet adapted — I am not going to do it in a near future, wait at least first user request).

> there will be some sort of docs for the new adaptation of electron-builder for proton

For now I have added to project readme: https://github.com/electron-userland/electron-builder#proton-native

Cross-platform building not yet supported (https://github.com/kusti8/proton-native/pull/57#issuecomment-375195543), Windows will be supported soon.

**Comment by parro-it** [comment]
@develar do you think electron-builder could be used directly with libui-node apps? Independently from proton-native I mean...

**Comment by develar** [comment]
@parro-it Yes. Actually, the only specific for proton-native in the [ProtonFramework](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/ProtonFramework.ts) implementation it is enabled by default babel transpilation (`createTransformer` function). So, if libui-node app it is just a bunch of source files to run using NodeJS, you can use electron-builder 20.7.1 to package it (set `protonNodeVersion` to NodeJS version or to `current`). If not — can be easily supported.

**Comment by mischnic** [comment]
@develar 
Works for proton-native (Mac). 👍 
Only problem: it says   `default Electron icon is used reason=application icon is not set`, but there is no icon used at all.

With libui-node: 
```
$ yarn build
yarn run v1.5.1
$ electron-builder --dir
  • electron-builder version=20.8.1
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/package.json
  • author is missed in the package.json appPackageFile=/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/package.json
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 proton=9.9.0 appOutDir=dist/mac
  • downloading               path=/Users/niklas/Library/Caches/electron-builder/node/node-9.9.0-darwin-x64 url=https://nodejs.org/dist/v9.9.0/node-v9.9.0-darwin-x64.tar.xz
  • default Electron icon is used reason=application icon is not set
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at ProtonFramework.createTransformer (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/src/ProtonFramework.ts:24:4)
    at MacPackager.copyAppFiles (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/src/platformPackager.ts:232:86)
    at /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/src/platformPackager.ts:192:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at MacPackager.doPack (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/out/platformPackager.js:374:7)
    at /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/out/macPackager.js:254:7)
    at /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/src/packager.ts:372:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at Packager.doBuild (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/out/packager.js:605:7)
    at /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/src/packager.ts:316:52
    at Generator.next (<anonymous>)
    at /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:153:20)
From previous event:
    at Packager._build (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/out/packager.js:532:7)
    at /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/src/packager.ts:289:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at Packager.build (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/out/packager.js:491:7)
    at /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder/src/builder.ts:229:10)
    at then (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at Object.args [as handler] (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at Object.runCommand (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad/node_modules/electron-builder/src/cli/cli.ts:28:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c electron-builder --dir
Directory: /Users/niklas/Desktop/DEV-TEST/libui/libui-nodepad
Output:
".
```
```
{
  "build": {
    "protonNodeVersion": "current"
  }
}
```

**Comment by develar** [comment]
For proton-native for now I have introduced new `Framework` property `isDefaultAppIconProvided`  and it is `false` for now (later (at least I after implementing cross-platform / Windows support) we can open discussion/issue about default icon for Proton Native apps (I think some default should be used to advertise that this app is a Proton and make it more clear during debug)).

I think I will add a new option `framework` and user will be able directly specify framework name (e.g. `libui `), since I definitely don't want to introduce `libuiNodeVersion`. And option `nodeVersion` will be added (not required, defaults to `current`) and applicable for `libui` and `proton`.

**Comment by albe-rosado** [comment]
this weekend i will take a close look to the behavior on linux, if it works, i will include it in the cli. this looks awesome

**Comment by mischnic** [comment]
@albe-rosado Any progress?

**Comment by albe-rosado** [comment]
nope, let me see when I get a chance, I have a lot going on right now, will try to see what is going on on electron-builder side first. and you?

**Comment by mischnic** [comment]
I only tried it out on macOS. Works fine

```json
{
	"name": "Notepad",
	"author": "test",
	"version": "1.0.0",
	"description": "a notepad app built using proton-native",
	"main": "index.js",
	"scripts": {
		"start": "babel-node index.js",
		"build": "electron-builder --dir",
		"package": "electron-builder"
	},
	"dependencies": {
		"proton-native": "^1.0.11"
	},
	"build": {
		"protonNodeVersion": "current",
		"mac": {
			"identity": null
		}
	},
	"devDependencies": {
		"babel-cli": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"babel-preset-react": "^6.24.1",
		"babel-preset-stage-0": "^6.24.1",
		"electron-builder": "*"
	}
}
```

**Comment by albe-rosado** [comment]
cool, will make this my priority, im excited we could have this figured out..... if you get the chance to test it on windows? lol

**Comment by mischnic** [comment]
>  if you get the chance to test it on windows

See https://github.com/kusti8/proton-native/issues/43#issuecomment-375207992:

> Upcoming electron-builder 21.7.0 supports packaging for macOS and Linux.
>
> - for Linux all functionality is supported, including auto-update (but only on low-level, client electron-updater is not yet adapted — I am not going to do it in a near future, wait at least first user request).
>
> - **Windows will be supported soon.**

**Comment by albe-rosado** [comment]
totally blind ... thanks

**Comment by albe-rosado** [comment]
I updated `create-proton-app` with the minimal electron-builder setup, tomorrow will update the docs and proton-native docs to reflect the requirements for windows. @mischnic @kusti8

**Comment by mischnic** [comment]
Could you please add
```json
"mac": {
  "identity": null
}
```
to the build config? Otherwise electron-build will try to use the first certificate it can find to sign the app (ignored on other platforms).

**Comment by develar** [comment]
Sorry for delay, I hope I will finish windows support in 2 weeks.

**Comment by kusti8** [comment]
That's great! Thanks.

**Comment by mischnic** [comment]
@develar What format should the default icon be in?

@kusti8 Are you ok with the one I made in https://github.com/kusti8/proton-native/issues/43#issuecomment-374736918 ?

**Comment by develar** [comment]
> What format should the default icon be in?

PNG (electron-builder is able to transform png to ico/icns automatically).

**Comment by kusti8** [comment]
Yeah I like the logo. Sounds good.

**Comment by develar** [comment]
I have converted provided SVG file to [ICNS](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/templates/proton-native.icns), electron-builder 20.14.3 uses it as a default icon for macOS.

**Comment by zlfnhmd** [comment]
Hey guys the status on windows support? @kusti8 @develar @mischnic

**Comment by mischnic** [comment]
In the meantime, I've set up an example for how to use [launchui-packager](https://github.com/mimecorg/launchui-packager) with proton-native: https://github.com/mischnic/proton-launchui.

**Comment by zlfnhmd** [comment]
@mischnic The main with [launchui-packager](https://github.com/mimecorg/launchui-packager) is updating the app after publishing. Is there any workaround for that?

**Comment by develar** [comment]
1. New option `framework` is added to support pure `libui`. One of `electron`, `proton-native`, `libui`. Defaults to `electron`. `proton` vs `libui` — for now, only babel is not used for libui. And libui is not tested at all. 
2. `nodeVersion` is added and option `protonNodeVersion` is deprecated. So, to build for proton, you now need to set framework to `proton`. And set `nodeVersion` if you want specific node version (see below why for now it doesn't taken in account for Linux/Windows).

3. electron-builder now supports building proton applications for Windows. Because libui currently doesn't provide prebuilt binaries, I decided to use [launchui](https://github.com/mimecorg/launchui). It means that now **you can build for Linux and Windows on any OS**.

    How does it work? app-builder instructed to exclude `libui-node` dependency during production dependency graph building. So, packed application doesn't have `libui-node` dependency (and all sub dependencies) at all. App deps located in `app/node_modules`. Launchui skeleton provides libui in root `node_modules`.

   So, you can build for Windows or Linux on any OS. Binaries available on https://github.com/develar/launchui/releases For now only `v0.1.4-10.13.0` is available (Node 10.13.0 LTS). It is easy to build for other version because `appveyor.yml` is provided (you can send PR and appveyour will build it and then you can grab artifacts and do not wait when it will be merged and released ;))

4. For Linux only x64 is supported (for bloody Windows I have set up AppVeyour, for Linux unexpectedly I also cannot build ia32, so, need to add Travis (it is required anyway for security reasons). If you don't want to use launchui for Linux and can build Proton app on Linux, set `"launchUiVersion": false` (obviously, this `false` is respected only for Linux). 

5. Default icon for Linux is fixed.

6. rcedit doesn't support LaunchUI on Wine (crashes). So, app installer will have correct meta info and icon (because of amazing NSIS), but installed app icon will be not. I found solution, but it will be implemented not in electron-builder 20.36.0

I think this issue can be closed. Further issue please file to electron-builder issue tracker (prefix with "proton: " to ensure that it will be fixed faster than electron framework issues ;)).

**Comment by develar** [comment]
What do you think about launchui? Right now, when no prebuild for libui, it is the only solution to build proton app on any OS for any OS. In case of Windows no variants — bat file or another script is not good. But for Linux and macOS... I am worry about fact that in case of LaunchUI user cannot easily use own node version. But... probably it is ok as I have prepared appveyor and so, it is easy to release new LaunchUI builds for new versions of libui/node.

**Comment by mischnic** [comment]
libui binaries are already available and libui-node prebuilds should be in the near future (not sure where I said that a few days ago - there are too many issues regarding the packaging 😄).
Is there really no other way than recompiling node to not always have a black command prompt window on Windows? (Only advantage of launchui on Linux/macOS: reporting fatal errors in a dialog instead of printing them to the console.)

**Comment by develar** [comment]
> Is there really no other way than recompiling node to not always have a black command prompt window on Windows?

Actually we can simply use link args as solution (for both desktop and start-up shortcuts). Another solution is VBScript. For me problem is that on bloody Windows I didn't managed to make libui working and instead of investigating WHY bloody libui-node cannot find compiled libui node native module I decided to just use launchui (I forked it and build using latest LTS node). Maybe on this weekend I will do another round of debugging libui-node and bloody windows.

**Comment by albe-rosado** [comment]
im replying form my phone, will reply when i get home in a few hours .

**Comment by develar** [comment]
BTW — I have security concerns of using node.exe directly with arg. Not sure are all antiviruses will be happy. It is why I gave up and started to use LaunchUI for Windows. Windows is so bad that it is better to avoid any unclear solution for packaging apps, that can be used in various conditions.

**Comment by develar** [comment]
Ok, I have managed to rebuild *** native module and now Windows is happy to run app and load native module directly without LaunchUI.

Problem is that Windows doesn't have such concept as application. On Linux or macOS you can define your application as unit, but on Windows it is just a bunch of files.

See screenshot.

<img width="386" alt="screenshot 2018-11-16 at 07 47 21" src="https://user-images.githubusercontent.com/350686/48602630-11dd6400-e974-11e8-9cbd-034b7da0b1e1.png">

Nice? Nice. So, user can by mistake run `notepad.exe` instead of `notepad` and then will be disappointed, because `notepad.exe` here it is just a plain node.exe that expects some args to run app. Of course, I am not Windows user, but I am sure that there are number of another such gotchas, that as result will ruin and discredit the whole idea to use libui apps.

Yes — we can name helper executable as `-helper` to make clear that it is an internal, sub executable.

Should we? I think we should not. The only price of LaunchUI — send PR once in several months to build a new release for recent libui/nodejs version. And as AppVeyour file to do it is provided, even if main maintainers doesn't provide required versions for you, it takes only [30-40](https://ci.appveyor.com/project/develar/launchui/builds/20329914) minutes (per arch) to build your own if need (fork repo, add project to AppVeyour, change [download-deps.json](https://github.com/develar/launchui/blob/master/tools/download-deps.json), wait 30 minutes and grab artifacts from build).

"avoid base binaries" vs "app will differ from native and consists of two executable (that will also slighly slowdown start because it is Windows)"

And don't tell me about AppX — thanks to Microsoft, this technology supported only on Windows 10 and so, we can use it only in 2030 or later.

**Comment by mimecorg** [comment]
Just to clarify, my intent is to maintain LaunchUI and keep releasing new versions, and the AppVeyor integration will definitely help with that, but first there must be some consensus whether it's the "right" solution or not.

**Comment by mischnic** [comment]
@develar In case you haven't seen it, [here](https://github.com/parro-it/libui-node/issues/113) is the initial "proposal" for launchui.

@mimecorg Could launchui just use the precompiled libui and libui-node (-napi) binaries once they're available?

**Comment by mimecorg** [comment]
> @mimecorg Could launchui just use the precompiled libui and libui-node (-napi) binaries once they're available?

It could, but I think that libui-node still has to be recompiled to link against node.dll instead of node.exe, even if it's using N-API.

**Comment by mischnic** [comment]
>  libui-node still has to be recompiled to link against node.dll instead of node.exe, even if it's using N-API.

I don't think so (at least on macOS). libui-napi isn't linked to anything regarding node. I'm guessing that everything of that is done when node loads the module at runtime.

```
ui.node:
	@rpath/libui.A.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

**Comment by develar** [comment]
> but first there must be some consensus whether it's the "right" solution or not.

NodeJS doesn't going to offer official solution — https://github.com/nodejs/node/issues/556 So, it means that for now even if you can build simple launcher like 

```go
package main

import (
  "os"
  "os/exec"
  "path/filepath"
)

func main() {
  ex, err := os.Executable()
  if err != nil {
    panic(err)
  }

  appDir := filepath.Dir(ex)

  command := exec.Command(filepath.Join(appDir, "node.exe"), filepath.Join(appDir, "app", "main.js"))
  command.Dir = appDir
  //command.Stdout = os.Stderr
  //command.Stderr = os.Stderr
  err = command.Run()
  if err != nil {
    panic(err)
  }
}
```

`GOOS=windows GOARCH=amd64 go build -ldflags='-s -w -H=windowsgui' -o dist/app-runner.exe`

you still have to rebuild node.exe. So, I see that LaunchUI is the only solution.

**Comment by antillgrp** [comment]
One question guys, will these executable (i.e. .exe) are going to be node independent, no node platform installed needed in the target machine, or am I still gonna need node installed to run it? 

Which as of right now the more straight forward solution? This https://github.com/kusti8/proton-native/issues/43#issuecomment-426370188 ?

**Comment by mischnic** [comment]
> One question guys, will these executable (i.e. .exe) be nodejs independent, no node platform installed needed in the target machine, or am I still gonna need node installed to run it?

They don't require node to be installed. And by now, electron-builder supports Windows with proton-native.

**Comment by antillgrp** [comment]
There was something I did not understand well, do I run that script over the folder (no matter how many js files are conforming the app) or do I have to consolidate everything in a single js file as was done for no notepad 1.0.1 explample?

**Comment by kusti8** [comment]
If you have installed proton native with create-proton-app, then you can just run `npm run build && npm run dist` to automatically create a packaged version. It will scan for all files.

**Comment by antillgrp** [comment]
Is there any way to create a single .exe file instead of an application folder full of dlls?

**Comment by yrik** [comment]
> And by now, electron-builder supports Windows with proton-native (so all platforms).

For some reason on their website they say that 
>Currently, only macOS and Linux supported.

See https://www.electron.build/configuration/configuration#proton-native

**Comment by yrik** [comment]
I'm having some strange issues with proton native and native packages (keytar),
https://github.com/electron-userland/electron-builder/issues/3736
Even super simple app built with create-proton-app and only keytar as a dependency fails when packaged with electron-builder. However, it works fine with `npm run start`

Maybe anyone has a quick idea on how to approach it?
