### ISSUE TITLE
Is Proton-native ready for production. Or is it still a hobby project 

### ISSUE THREAD

**Issue by herlarb** [kusti8/proton-native#64]
This is not an issue per se. But can Proton-native be used for production or is it still an hobby project. I am a part-time Qt developer and I have been actively using React and React-native for about a year now.

**Comment by kusti8** [comment]
Proton-native itself is pretty stable, most of the fixes are just small fixes in code quality and documentation. It depends on whether you see `libui` as stable. I see it as stable enough for many projects, but if you're going to be doing something very complex where you want years of development on your side, you're never going to beat Qt.

But if you want to make something quickly and easily, which can still pretty much stand the test of time since `libui` is written using native GUI libraries, then `proton-native` is a good choice.

Ultimately, it's up to you.

**Comment by herlarb** [comment]
But it can't be styled as far as i see it. Is there any way to style components without having to give then native "look and feel".

**Comment by kusti8** [comment]
No you can't style, that's a fundamental difference.

**Comment by mischnic** [comment]
Something that's coming in the future:

![bildschirmfoto 2018-03-22 um 17 24 12](https://user-images.githubusercontent.com/4586894/37783540-09351bde-2df6-11e8-82e9-843b15d1b0f6.png)
